[build]
builder = "nixpacks"
buildCommand = "cd ../.. && bun install && cd app/packages/api && bunx prisma generate && bun run build"

[deploy]
startCommand = "bun run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
